var mongoose    = require("mongoose");
var Product = require("../models/product");
var Order = require("../models/order");
var User = require("../models/user");

mongoose.set('useNewUrlParser', true);
mongoose.set('useUnifiedTopology', false);

var url = process.env.DATABASEURL || "mongodb://localhost/medlife" ;
mongoose.connect("mongodb+srv://shubh:medeasy@cluster0-tikja.mongodb.net/test?retryWrites=true&w=majority");


var products = [
    new Product({
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5x3-4aTyaiQUvRWPtudzSAQi0LRLKE_FtwEQUmHanpxiCxja3&s',
        title: 'Etymology',
        description: ' It helps to cut down calories and manages the sugar level.',
        price: '50',
        qty: '5',
        _tags: ['diabetes'],
        category: "diabetic-care",
        composition: 'Dextrose that are derived from sugar.',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'johnsons',
        precautions: 'Keep away from direct sunlight.',
        tablets: '10 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/SUGARTN18A/SUGARTN18A-1.jpg?id=2020-04-08-08:49:06.138000',
        title: 'Sugar Free Gold Pellets',
        description: 'Sugar free Gold Pellets is a low-calorie sugar substitute. It helps to cut down calories and manages the sugar level. It gives same taste as sugar.',
        price: '237',
        qty: '15',
        _tags: ['weight watchers', 'diabetes','cholesterol'],
        category: "diabetic-care",
        composition: 'It contains Aspartame, Maltodextrin, and Dextrose that are derived from sugar.',
        mfgDate: '01/01/2019',
        expDate: '01/07/2023',
        brand: 'Sugar Free ',
        precautions: 'Keep away from direct sunlight,Store in a dry place,Keep away from children',
        tablets: '500 Pcs '
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/SRISRTB65A/SRISRTB65A.jpg?id=2020-04-13-06:57:41.381000',
        title: 'Sri Tattva Mehantaka Vati',
        description: 'Take 2 tablets twice a day or as per directed by the physician',
        price: '207',
        qty: '',
        _tags: ['Vati'],
        category: "diabetic-care",
        composition: 'Nimba,Gokshuru,Amruth,Methi',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'SRi SRi Tattva',
        precautions: 'Store in a cool place. Keep away from direct sunlight.',
        tablets: '60 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/ORGANTP01A/ORGANTP01A-1.jpg?id=2020-04-08-08:48:50.643000',
        title: ' Tulsi Green Tea Classic Tea Bag',
        description: 'Make your teatime pure pleasure with a sip of Organic India Tulsi Green Tea Classic Tea! Its a blend of Tulsi and Green Tea that promotes healthy metabolism, helps in better digestion and boosts immunity. Abundant in antioxidants, this flavored tea also aids in weight loss and uplifts mood.',
        price: '147',
        qty: '20',
        _tags: ['tea'],
        category: "diabetic-care",
        composition: 'Green Tea (Camellia sinensis),Rama Tulsi (Ocimum Sanctum),Krishna Tulsi (Ocimum Sanctum),Vana Tulsi (Ocimum Gratissimum)',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Originic India',
        precautions: 'Keep away from direct sunlight',
        tablets: '25 Bags'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/DIABETN01A/DIABETN01A-1.jpg?id=2020-04-13-06:57:33.954000',
        title: 'Diabecon DS',
        description: 'Himalaya Diabecon is a proprietary Ayurvedic medicine that helps to fight against diabetes. The key ingredients Meshashringi, Pitasara and Shilajeet stimulates the production of   insulin. It is more effective for newly detected diabetic patients. ',
        price: '144',
        qty: '12',
        _tags: ['diabetes','blood-sugar'],
        category: "diabetic-care",
        composition: 'Gymnema (Meshashringi), Indian Kino Tree s (Pitasara) and Shilajeet',
        mfgDate: '29/04/2018',
        expDate: '29/04/2020',
        brand: 'Himalaya',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '60 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/DIABETB02A/DIABETS05A.jpg?id=2020-03-03-09:30:40.967000',
        title: 'Diabetasafe',
        description: 'Oral Hypoglycermic Agent (OHAs)',
        price: '1648',
        qty: '16',
        _tags: ['diabetes'],
        category: "diabetic-care",
        composition: 'Gymnema Sylvestre 100Mg,Enicostemma Littorale 50 Mg,Pterocarpus Marsupium 95 Mg,Syzygium Cuminii 30 Mg,Emblica Officinalis 75 Mg',
        mfgDate: '01/12/2017',
        expDate: '01/02/2019',
        brand: 'MedEasy Essential',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '180 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/DRRECDB49A/DRRECDB49A.jpg?id=2020-04-08-08:49:30.278000',
        title: 'Dr. Reckeweg R40 Diabetes Drops',
        description: 'Direction for Use:As a prolonged cure, 3 times daily 10-15 drops in a little water before meals',
        price: '308',
        qty: '5',
        _tags: ['diabetes'],
        category: "diabetic-care",
        composition: 'Acidium phosphoricum,,Arscenicum,Lycopdium',
        mfgDate: '22/02/2019',
        expDate: '22/08/2024',
        brand: 'Dr. Reckeweg',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '22 ml'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/DABURAJ01A/DABURAJ01A-1.jpg?id=2020-04-09-12:59:25.071000',
        title: 'Dabur Chyawanprash Awaleha',
        description: 'Dabur Chyawanprash Awalehya is a unique combination of herbs and plant extract. It strengthens your body defense mechanism which helps to fight infections like cold, cough, etc.',
        price: '308',
        qty: '13',
        _tags: ['immunity','better_digestion'],
        category: "ayurveda",
        composition: 'Amla, Giloy, Karkatshringi, Bhumiamlaki, Bedarikand, Bala and Mustak ',
        mfgDate: '03/06/2018',
        expDate: '03/12/2020',
        brand: 'Dabur',
        precautions: 'Store in a cool place. Keep away from direct sunlight.',
        tablets: '1 Kg'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/LIV52TN01A/LIV52TN01A-1.jpg?id=2020-04-08-08:49:11.083000',
        title: 'Himalaya Liv 52 DS 60 Tablets',
        description: 'Himalaya Liv 52 DS (Double Strength) is a hepatospecific formulation designed to improves the efficiency of the liver. It has antioxidant properties that help to prevent and treat viral hepatitis, alcoholic liver disease, pre-cirrhotic conditions and early cirrhosis, anorexia, loss of appetite and liver damage due to radiation therapy.',
        price: '126',
        qty: '9',
        _tags: ['liver_diseases','hepatitis'],
        category: "ayurveda",
        composition: 'Chicory,Arjuna,Jhavuka,Himsra',
        mfgDate: '17/02/2018',
        expDate: '17/02/2020',
        brand: 'Himalaya ',
        precautions: 'Keep away from direct sunlight. Keep out of reach of children. Keep it in a cool and dry place. Do not refrigerate.',
        tablets: '60 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/SEPTITN12A/SEPTITN12A.jpg?id=2020-04-09-12:59:26.822000',
        title: 'Septilin Tablets',
        description: 'Himalaya Septilin is an ayurvedic medicine that helps to boost immunity and fights against chronic infections. It has anti-infective therapy that stimulates the formation of antibodies. Available in syrup and tablet forms',
        price: '126',
        qty: '8',
        _tags: ['immunity','UTI','increase WBC'],
        category: "ayurveda",
        composition: 'Tinospora Gulancha (Guduchi), Licorice (Yashtimadhu) and Indian Bdellium (Guggulu)',
        mfgDate: '15/05/2017',
        expDate: '15/05/2022',
        brand: 'Himalya',
        precautions: ' Keep away from direct sunlight. ',
        tablets: '60 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/MEDLITB09A/MEDLITB09A.jpg?id=2020-03-03-10:43:53.504000',
        title: 'Moringa Tablets',
        description: 'Moringa Tablet is the combination of Moringa extract and Moringa powder. In Ayurveda, Moringa is popular as Shigru and is used as Balya (tonic) and Rasayana (rejuvenator). It contains nutrients such as β-carotene, Vitamins (A, B, C, D, E and K) and minerals which provide nutrition to the body.',
        price: '359',
        qty: '14',
        _tags: ['anemia','muscle_buildibg','malnutrition'],
        category: "ayurveda",
        composition:'Moringa oleifera',
        mfgDate: '22/08/2018',
        expDate: '22/08/2020',
        brand: 'MedEasy Essentials',
        precautions: 'Store at room temperature (25-30°C). Protect from moisture and light. Keep container tightly closed. Keep out of reach of children.',
        tablets: '30 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/ARTHPTB01A/ARTHPTB01A%20(1).jpg?id=2020-03-03-07:45:23.610000',
        title: 'Arthprotect Tablets',
        description: 'Medlife essentials arthprotect is a safe and effective herbal formulation useful in the management of pain and inflammation associated with joint disorders. It has anti-inflammatory and analgesic effects which help prevent cartilage surface degradation and manages joint tissues.',
        price: '599',
        qty: '15',
        _tags: ['Joint-tissue','knee-pains','immunity'],
        category: "ayurveda",
        composition: 'Boswellia Serrata, Commiphora Mukul,Withania Somnifera, Vitex Negundo',
        mfgDate: '18/09/2019',
        expDate: '18/09/2022',
        brand: 'MedEasy Essentials',
        precautions: 'Store Arthprotect tablets in a cool, dry place, away from direct sunlight. Do not refrigerate or freeze.',
        tablets: '60 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/GASEXTB01A/GASEXTB01A-1.jpg?id=2020-04-13-06:57:33.070000',
        title: 'Gasex Tablets',
        description: 'Gasex tablets invented by Himalaya is to award you with ultimate comfort and relief from abdominal problems such as gastric, indigestion, belching, flatulence and more. ',
        price: '108',
        qty: '20',
        _tags: ['indigestion'],
        category: "ayurveda",
        composition:'Cowrie Shell calx, onch shell Calx Black pepper',
        mfgDate: '27/02/2015',
        expDate: '27/02/2020',
        brand: 'Himalaya',
        precautions: 'Keep away from direct sunlight',
        tablets: '100 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/PILEXTN01A/PILEXTN01A-1.jpg?id=2020-04-13-06:57:33.225000',
        title: 'Pilex Tablets',
        description: 'Himalaya Pilex Tablet is a unique formulation of Sensitive plant and Zinc Calx that helps to treat hemorrhoids. It shrinks pile mass, controls bleeding and heals inflamed skin and the mucus membrane. ',
        price: '112',
        qty: '30',
        _tags: ['piles','reduce_pain'],
        category: "ayurveda",
        composition: 'Sensitive plant (Lajjalu) and Zinc Calx (Yashad bhasma) ',
        mfgDate: '17/09/2019',
        expDate: '17/09/2022',
        brand: 'Himalaya',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '60 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/MULTITB03A/MULTITB03A-1.jpg?id=2020-03-06-10:00:00.203000',
        title: 'MedEasy Essentials Multivitamin Tablets',
        description: 'MVM Tablet is a convenient, comprehensive and reliable supplement to fulfill the body’s micronutrient requirement on a daily basis. ',
        price: '299',
        qty: '30',
        _tags: ['anxiety','stress'],
        category: "nutritions",
        composition: 'Vitamins, Minerals, Gingko Biloba, Spirulina, Curcuma, Pine bark, Ginseng, Ginger, Brahmi, Garlic, Black Pepper, Alpha- Lipoic – Acid, Lycopene, Lutein, Choline, Inositol, and Amino Acids ',
        mfgDate: '17/08/2019',
        expDate: '17/08/2022',
        brand: 'MedEasy Essentials ',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '30 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/CALCITB05A/CALCITB05A-1.jpg?id=2020-03-06-09:59:58.871000',
        title: 'MedEasy Essentials CalciumTablets',
        description: 'Medlife Essential Calcium Tablet contains the combination of calcium citrate malate, vitamin D3, magnesium hydroxide and zinc sulphate',
        price: '299',
        qty: '18',
        _tags: ['teeth','bone'],
        category: "nutritions",
        composition: ' ',
        mfgDate: '17/09/2019',
        expDate: '17/09/2022',
        brand: 'MedEasy Essentials',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '60 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/REVITCB01A/REVITCB01A.jpg?id=2020-04-08-08:28:56.398000',
        title: 'Revital H Daily Health Supplement Capsules',
        description: 'Revital H Tablet is a multivitamin supplement which is a healthy combination of 12 Vitamins, 10 Minerals and Ginseng to improve immunity and keep you physically active throughout the day. These capsules help to prevent fatigue and weakness as well as enhance the concentration level.',
        price: '462',
        qty: '0',
        _tags: ['immunity'],
        category: "nutritions",
        composition: 'vitamins,minerals,ginseng',
        mfgDate: '11/01/2018',
        expDate: '11/01/2022',
        brand: 'Revital',
        precautions: 'Keep away from direct sunlight. ',
        tablets: '60 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/OSTOCTB04A/OSTOCTB04A-1.jpg?id=2020-04-08-08:49:35.550000',
        title: 'Ostocalcium Plus Tablets',
        description: 'Maintain healthy and strong bones with Ostocalcium Tablet! This chewable calcium tablet contains calcium and phosphorus, minerals which are the building blocks of bones. It also contributes to the normal function of digestive enzymes and plays a role in the process of cell division and specialization.',
        price: '147',
        qty: '3',
        _tags: ['string_bones'],
        category: "nutritions",
        composition: 'calcium and phosphorus, minerals ',
        mfgDate: '7/09/2019',
        expDate: '7/09/2020',
        brand: 'Ostocalcium',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '30 tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/ENSURPR03A/ENSURPR03A-1.jpg?id=2020-04-13-06:57:32.567000',
        title: 'Ensure Nutrition - Vanilla Refill',
        description: 'Ensure Chocolate is a complete and balanced health drink to ensure healthy and active life. The active ingredients with protein, fats and carbohydrates help to fill the everyday nutrition gaps. Scientifically formulated with slow release energy system to maintain energy levels, boost immunity and support weight management.',
        price: '1021',
        qty: '5',
        _tags: ['weight_loss','loss_if_appetite'],
        category: "nutritions",
        composition: 'Loaded with the goodness of 37 essential vital nutrients,Gluten-free Drink,Contains 100% vegetable fat ',
        mfgDate: '17/09/2018',
        expDate: '17/09/2020',
        brand: 'Ensure',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '1 Kg'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/PEDIAPR03A/8904145911196__1_.jpg?id=2020-04-13-06:57:36.500000',
        title: 'PediaSure Premium Chocolate Refill ',
        description: 'Pediasure Complete Chocolate Powder is one of the best nutritional drinks for kids between 2-10 years of age. It’s a perfect blend of a great chocolate taste and balanced nutritions which help in bringing out the goodness of calcium in milk. This powder is enriched with 37 vital nutrients that improve weight, immunity and brain development. Apart from essential vitamins, it also contains probiotics and prebiotic FOS that makes the bone strong. If your child is a fussy eater then it’s the perfect diet to fill all the nutritional gap',
        price: '520',
        qty: '12',
        _tags: ['immunity','brain_development','increase height and weight'],
        category: "nutritions",
        composition: 'Loaded with the goodness of 37 essential vital nutrients,Gluten-free Drink,Contains 100% vegetable fat ',
        mfgDate: '11/09/2019',
        expDate: '11/09/2022',
        brand: 'Pediasure',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '400 gm'
    }),
    new Product({
        image: 'https://www.netmeds.com/images/product-v1/150x150/390309/a_cn_gel_topical_20gm_0.jpg',
        title: 'A CN Gel(Topical) ',
        description: 'IT is used to treat  Mild to moderate acne (spots)',
        price: '135',
        qty: '10',
        _tags: ['moderate acne'],
        category: "medicines",
        composition: 'CLINDAMYCIN 1%+NICOTINAMIDE 4%',
        mfgDate: '2/03/2019',
        expDate: '2/09/2022',
        brand: 'Eskon Pharma',
        precautions: 'Are allergic (hypersensitive) to the active substance Clindamycin phosphate, Nicotinamide or any of the other ingredients.Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '20 gm'
    }),
    new Product({
        image: 'https://www.netmeds.com/images/product-v1/150x150/340387/crocin_pain_relief_tablet_15_s_0.jpg',
        title: 'Crocin Pain Relief Tablet',
        description: 'It is used to treat headache, migraine, backache, rheumatic and muscle pain, toothache and period pain .It also relieves discomfort in cold, influenza, sore throat and help reduce temperature',
        price: '59',
        qty: '30',
        _tags: ['Pain','Headache','Muscle Pain'],
        category: "medicines",
        composition: 'CAFFEINE 50MG+PARACETAMOL(ACETAMINOPHEN) 650MG',
        mfgDate: '22/03/2019',
        expDate: '22/09/2022',
        brand: 'Crocin',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '15 tablets'
    }),
    new Product({
        image: 'https://www.netmeds.com/images/product-v1/150x150/845421/creon_10000_capsule_15_s_0.jpg',
        title: 'Creon 10000 Capsule',
        description: 'https://www.netmeds.com/images/product-v1/150x150/845421/creon_10000_capsule_15_s_0.jpg',
        price: '544',
        qty: '15',
        _tags: ['Digestion'],
        category: "medicines",
        composition: 'PANCREATIN 150MG',
        mfgDate: '25/03/2019',
        expDate: '25/07/2022',
        brand: 'Abbott India',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '15 tablets'
    }),
    new Product({
        image: 'https://res.cloudinary.com/du8msdgbj/image/upload/l_watermark_346,w_240,h_240/a_ignore,w_240,h_240,c_fit,q_auto,f_auto/v1584535830/ceravg5bxpxcudjengn4.jpg',
        title: 'Combiflam Tablet',
        description: 'ombiflam Tablet contains two painkiller medicines. They work together to reduce pain, fever, and inflammation. It is used to treat many conditions such as headache, muscle pain, pain during periods, toothache and joint pain.',
        price: '34',
        qty: '25',
        _tags: ['fever','Reduce pain','inflammatiion'],
        category: "medicines",
        composition: 'Ibuprofen (400mg) + Paracetamol/Acetaminophen (325mg)',
        mfgDate: '20/06/2019',
        expDate: '22/09/2022',
        brand: 'Sanofi India',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '20 tablets'
    }),
    new Product({
        image: 'https://res.cloudinary.com/du8msdgbj/image/upload/l_watermark_346,w_240,h_240/a_ignore,w_240,h_240,c_fit,q_auto,f_auto/v1537725689/oiqyzxnyxyixjyl9xw2c.jpg',
        title: 'Cheston Cold Tablet',
        description: 'Cheston Cold Tablet is used in the treatment of common cold symptoms like runny nose, stuffy nose, sneezing, watery eyes and congestion or stuffiness. It is also used to relieve pain and fever.Cheston Cold Tablet is taken with or without food in a dose and duration as advised by the doctor. The dose you are given will depend on your condition and how you respond to the medicine',
        price: '39',
        qty: '2',
        _tags: ['runny nose','sneezing','fever'],
        category: "medicines",
        composition: 'Cetirizine (5mg) + Paracetamol/Acetaminophen (325mg) + Phenylephrine (10mg)',
        mfgDate: '2/03/2019',
        expDate: '2/03/2022',
        brand: 'Cipla',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '10 tablets'
    }),
    new Product({
        image: 'https://res.cloudinary.com/du8msdgbj/image/upload/l_watermark_346,w_240,h_240/a_ignore,w_240,h_240,c_fit,q_auto,f_auto/v1537723720/ruma122iif8yx1nwhpfe.jpg',
        title: 'Ascoril LS Syrup',
        description: 'Ascoril LS Syrup is a combination medicine used in the treatment of cough with mucus. It thins mucus in the nose, windpipe and lungs, making it easier to cough out. It also provides relief from runny nose, sneezing, itching, and watery eyes.',
        price: '83',
        qty: '10',
        _tags: ['watery eyes','itching'],
        category: "medicines",
        composition: 'Ambroxol (30mg/5ml) + Levosalbutamol/Levalbuterol (1mg/5ml) + Guaifenesin (50mg/5ml)',
        mfgDate: '22/03/2019',
        expDate: '22/09/2022',
        brand: 'Cipla',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: ' tablets'
    }),
    new Product({
        image: 'https://res.cloudinary.com/du8msdgbj/image/upload/l_watermark_346,w_240,h_240/a_ignore,w_240,h_240,c_fit,q_auto,f_auto/v1537728799/xdqmtonvhlqoxgbzqiub.jpg',
        title: 'Montek LC Tablet',
        description: 'Montek LC Tablet is a combination medicine used in the treatment of allergic symptoms such as runny nose, stuffy nose, sneezing, itching, swelling, watery eyes and congestion or stuffiness. It also reduces inflammation in the airways and make breathing easier.',
        price: '163',
        qty: '0',
        _tags: ['watery eyes','itching'],
        category: "medicines",
        composition: 'Levocetirizine (5mg) + Montelukast (10mg)',
        mfgDate: '2/03/2018',
        expDate: '2/09/2020',
        brand: 'Cipla',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '10 tablets'
    }),
    new Product({
        image: 'https://res.cloudinary.com/du8msdgbj/image/upload/l_watermark_346,w_240,h_240/a_ignore,w_240,h_240,c_fit,q_auto,f_auto/v1535629115/nlyvmplrslu6jmrozmf5.jpg',
        title: 'Nurokind-LC Tablet',
        description: 'Nurokind-LC Tablet is a prescription medicine. It has a combination of vitamins that is prescribed to treat vitamin and other nutritional deficiencies. It ensures the proper growth and functioning of the body.',
        price: '164',
        qty: '5',
        _tags: ['vitamin deficiency','nutrition deficiency'],
        category: "medicines",
        composition: 'Levo-carnitine (500mg) + Methylcobalamin/Mecobalamin (1500mcg) + Folic Acid (1.5mg)',
        mfgDate: '22/03/2019',
        expDate: '22/09/2022',
        brand: 'Mankind',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '15 tablets'
    }),
    new Product({
        image: 'https://res.cloudinary.com/du8msdgbj/image/upload/l_watermark_346,w_240,h_240/a_ignore,w_240,h_240,c_fit,q_auto,f_auto/v1537708780/pwu04ahkoxrkjd27xjql.jpg',
        title: 'O2 Tablet',
        description: 'O2 Tablet is a combination of two antibiotics that effectively kills the microorganisms. It is used to treat gynecological infections, lung infections, urinary infections, and gastrointestinal infections such as acute diarrhea or dysentery.',
        price: '116',
        qty: '15',
        _tags: ['ling infection'],
        category: "medicines",
        composition: 'Ofloxacin (200mg) + Ornidazole (500mg)',
        mfgDate: '22/03/2019',
        expDate: '22/09/2022',
        brand: 'Mankind',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight. ',
        tablets: '10 tablets'
    }),
    // new Product({
    //     image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYgnFnlm_mQJU16HOxf-W6JKB351U5MMmJcNGQxima_Mp5Y9xIbw&s',
    //     title:  'Dulcolax',
    //     description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     price: '250',
    //     qty: '5',
    //     _tags: ['cough','cold'],
    //     category: "medicines",
    //     composition: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     mfgDate: '10/02/2019',
    //     expDate: '10/02/2022',
    //     brand: 'johnsons',
    //     precautions: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     tablets: '10 tablets'
    // }),
    // new Product({
    //     image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTch_xnS2RG8etW6r6vveUYXuJ4xhN9f7ewPmWOtUxolpjGtSrHpw&s',
    //     title: 'Benadryl',
    //     description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     price: '345',
    //     qty: '5',
    //     _tags: ['cough'],
    //     category: "medicines",
    //     composition: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     mfgDate: '10/02/2019',
    //     expDate: '10/02/2022',
    //     brand: 'johnsons',
    //     precautions: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     tablets: '10 tablets'
    // }),
    // new Product({
    //     image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5x3-4aTyaiQUvRWPtudzSAQi0LRLKE_FtwEQUmHanpxiCxja3&s',
    //     title: 'Etymology',
    //     description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     price: '50',
    //     qty: '5',
    //     _tags: ['cough','xyz'],
    //     category: "diabetic-care",
    //     composition: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     mfgDate: '10/02/2019',
    //     expDate: '10/02/2022',
    //     brand: 'johnsons',
    //     precautions: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     tablets: '10 tablets'
    // }),
    // new Product({
    //     image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBQ-aranOoWPvtujWlETwEU36TO3X5z295yFJcDzKRXk1_HNk-bQ&s',
    //     title: 'Listerine',
    //     description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     price: '600',
    //     qty: '5',
    //     _tags: ['xyz'],
    //     category: "personal-care",
    //     composition: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     mfgDate: '10/02/2019',
    //     expDate: '10/02/2022',
    //     brand: 'johnsons',
    //     precautions: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     tablets: '10 tablets'
    // }),
    // new Product({
    //     image: 'https://healthwatched.files.wordpress.com/2014/12/veenat400mg.jpg',
    //     title: 'Veenat 400',
    //     description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     price: '400',
    //     qty: '5',
    //     _tags: ['cough'],
    //     category: "ayurveda",
    //     composition: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     mfgDate: '10/02/2019',
    //     expDate: '10/02/2022',
    //     brand: 'johnsons',
    //     precautions: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id obcaecati a ducimus ex sed necessitatibus!',
    //     tablets: '10 tablets'
    // }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/CETAPLB05A/CETAPLB05A-1.jpg?id=2020-04-08T08:49:48.284000+00:00',
        title: 'Cetaphil Gentle Skin Cleanser',
        description: 'A mild, soap-free face and body cleanser that hydrates and soothes skin as it cleans.',
        price: '255',
        qty: '5',
        _tags: ['skin'],
        category: "personal-care",
        composition: 'Water, Cetyl Alcohol, Propylene Glycol, Sodium Lauryl Sulfate, Stearyl Alcohol, Methylparaben, Propylparaben, Butylparaben',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Cetaphil ',
        precautions: 'Directions for use without water: Apply a liberal amount of cleanser to the skin and rub gently.Remove excess with a soft cloth, leaving a thin film on the skin.Directions for use with water: Apply cleanser to the skin and rub gently. Rinse.',
        tablets: '125 ml'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/SENQUPN04A/SENQUPN04A.jpg?id=2020-04-08-08:40:51.741000',
        title: 'Senquel F Oral Gel',
        description: 'A toothpaste that address oral problems.',
        price: '99',
        qty: '5',
        _tags: ['oral'],
        category: "personal-care",
        composition: 'Potassium Nitrate,Triclosan,Fluride medicated oral gel',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Senquel',
        precautions: 'Apply liberal amount of tooth paste onto the tooth brush and brush for about 2-3 minutes.Rinse with water and spit out the foam. Do not swallow.',
        tablets: '100 gm'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/BOROLCT03A/BOROLCT03A.jpg?id=2020-04-08-08:41:09.461000',
        title: 'Boroline Antiseptic Ayurvedic Cream',
        description: 'Boroline Antiseptic Ayurvedic Cream is a luxuriantly rich night repair cream to heal dry and rough skin overnight. Use Boroline every night and wake up every morning with soft, happy skin.',
        price: '42',
        qty: '5',
        _tags: ['skin'],
        category: "personal-care",
        composition: 'Boric Acid:Boric Acid has mild anti bacterial and anti fungal properties,Zinc Oxide:Zinc Oxide is a mild astringent for the skin and has a soothing and protective action in skin infections.',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Boroline',
        precautions: 'Do not use Boroline on pimples which occur due to excessive oil secretion. Boroline being oily itself will aggravate the problem.Do not apply Boroline on very deep wounds, which are raw and weeping. Keep such wounds dry and covered, preferably washing with Suthol twice a day and using medication as per Doctor’s advice. Cover with cotton and a clean gauge that allows air circulation.',
        tablets: '20 gm'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/HIMALFT41A/HIMALFT41A.jpg?id=2020-04-08-08:48:58.670000',
        title: 'Himalaya Purifying Neem Facewash',
        description: 'Get rid of troublesome pimples and acne with Himalaya Purifying Neem Face Wash. This herbal formulation cleans impurities and helps clear pimples. A natural blend of Neem and Turmeric bring together their antibacterial and antifungal properties improve general skin health and help to even out your skin tone. It also enhances the blood circulation and clears clogged pores. Suitable for all skin types. Best for acne-prone skin.',
        price: '243',
        qty: '5',
        _tags: ['face-care'],
        category: "personal-care",
        composition: 'Neem,Turmeric',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Himalaya ',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight.',
        tablets: '300ml'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/HIMALBB02A/HIMALBB02A.jpg?id=2020-04-08-08:41:00.074000',
        title: 'Himalaya Lip Balm ',
        description: 'Heal dry and chapped lips with Himalaya Lip Balm. This lip balm moisturizes your lips to keep them soft and supple. The moisture-retention formula with skin soothers makes lips naturally glossy while the antioxidants and natural actives care for your lips by protecting them from environmental damage. Enriched with 100% natural color, Vitamin E and antioxidants, this lip balm is free of preservatives, petroleum jelly, mineral oil and silicone.',
        price: '27',
        qty: '5',
        _tags: ['lip-care'],
        category: "personal-care",
        composition: 'Carrot Seed Oil,Wheat Germ Oil,Sweet Indrajao,Coconut Oil,Castor Oil',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Himalaya',
        precautions: 'Keep out of reach of children. Keep away from direct sunlight.',
        tablets: '10gm'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/SEBAMFB01A/SEBAMFB01A-1.jpg?id=2020-03-10-07:54:57.409000',
        title: 'Sebamed Clear Face Cleansing Foam',
        description: 'Sebamed Clear Face Cleansing Foam helps fights pimples and supports healthy facial skin. It helps keep the skin hydrated, makes the skin feel refreshed. It aids in removing impurities.     ',
        price: '522',
        qty: '5',
        _tags: ['face'],
        category: "personal-care",
        composition: 'Not mentioned',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Sebamed',
        precautions: 'Keep away from direct sunlight,Store in dry place,Keep away from children',
        tablets: '150 ml'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/DABURRB02A/DABURRB02A.jpg?id=2020-04-08-08:40:44.401000',
        title: 'Dabur Gulabari Premium Rose Water',
        description: 'About Brand:Founded in 1884, Dabur is one of the market leaders which is dedicated to the health and wellness worldwide. Dabur focuses on manufacturing the product naturally. All the products of Dabur are paraffin-free, dermatologically tested and free from any artificial color.',
        price: '70',
        qty: '5',
        _tags: ['skin'],
        category: "personal-care",
        composition: 'rose extract,chandan',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Dabur ',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '250 ml'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/SIMILPJ11A/SIMILPJ11A-1.jpg?id=2020-03-10-09:23:06.026000',
        title: 'Similac IQ+ Stage 3 Formula Jar',
        description: 'Similac IQ + Stage 3 with DHA supports mental and physical growth. It contains DHA, lutein, vitamin E, omega 3, iron, taurine, iodine, folic acid and zinc.',
        price: '650',
        qty: '5',
        _tags: ['baby wellness'],
        category: "baby-and-mom-care",
        composition: 'Milk Solids, Maltodextrin, Demineralised whey, Low erucic rapeseed oil, Coconut oil, High oleic sunflower oil, Sunflower oil, Minerals, Soya lecithin, Vitamins, Nucleotides and Acidity regulator (Citric acid)',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Similac',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '400 GM'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/GRIPELN04A/GRIPELN04A.jpg?id=2020-04-08-08:40:54.839000',
        title: 'Woodwards Gripe Water',
        description: '5ml spoonful dosage for 1-6 months babies.',
        price: '45',
        qty: '5',
        _tags: ['baby wellness'],
        category: "baby-and-mom-care",
        composition: 'Terpeneless Dill Seed Oil,Sodium Hydrogen Carbonate,Glycerol,Maltitol Liquid,Sodium',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Woodwards',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '130ml'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/BONNISN02A/BONNISN02A%20(2).jpg?id=2020-04-08-08:40:59.723000',
        title: 'Himalaya Bonnisan Syrup',
        description: 'Treats infants and children suffering from infantile colic, diarrhea, abdominal pain and dyspepsia,Provides relief from acidity and gas,Treats stomach pain in children and infants',
        price: '75',
        qty: '5',
        _tags: ['baby wellness'],
        category: "baby-and-mom-care",
        composition: 'Dill Oil,Indian Gooseberry,Tinospora Gulancha',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Himalaya ',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '200ml'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/CETAPLB01A/CETAPLB01A-1.jpg?id=2020-03-24-05:19:15.368000',
        title: 'Cetaphil Baby Daily Lotion ',
        description: 'This gentle baby lotion is designed to soothe and nourish, while moisturizing and protecting your baby’s skin from dryness. It is specially formulated with soothing organic calendula extract, derived from the marigold flower and used for centuries to soothe dry, sensitive skin.',
        price: '575.4',
        qty: '5',
        _tags: ['baby-lotion'],
        category: "baby-and-mom-care",
        composition: 'Water, Sorbitol, Helianthus Annuus (Sunflower) Seed Oil, Isopropyl Palmitate, Octyldodecanol, Polyglyceryl-3 Diisostearate, Glycerin, Panthenol (Vitamin B5), Hexyldecanol, Hexyldecyl Laurate, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Caprylyl Glycol, Carbomer, Fragrance, Disodium Cocoyl Glutamate, Sodium Hydroxide, Dipropylene Glycol, Calendula Officinalis Flower Extract, Squalane, Propylene Glycol, Glyceryl Caprylate, Heliotropine, Tocopherol (Vitamin E), Glycine Soja (Soybean) Oil',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Cetaphil ',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '400ml'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/SEBAMSN01A/SEBAMSN01A.jpg?id=2020-04-08-08:48:55.285000',
        title: 'Sebamed Baby Cleansing Bar',
        description: 'Sebamed Baby Cleansing Soap is the combination of wheat germ oil, amino acid and vitamins to nourish and moisturize babys skin. Its a sugar-based cleanser and has pH value 5.5 to maintain the moisture equilibrium and prevent from dry skin.',
        price: '265',
        qty: '5',
        _tags: ['Baby Cleansing Bar'],
        category: "baby-and-mom-care",
        composition: 'Bee Wax,Wheat Germ Oil,Panthenol',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Sebamed',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '100gm'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/HIMALPJ03A/HIMALPJ03A.jpg?id=2020-04-08-08:41:03.180000',
        title: 'Himalaya Baby Powder ',
        description: 'Himalaya Baby Powder is a specially formulated powder that gives complete protection against all types of rashes. It absorbs wetness, reduces irritation and helps to soothe baby’s skin. It is enriched with nourishing elements like olive oil, almond oil, khus khus and natural zinc that effectively soothe your babys delicate skin. Olive oil has the goodness of Vitamin E and is known to soften and protect your childs skin while preventing dermatitis and other skin problems like chaffing. Vitamin A-enriched almond oil fights infections and contributes to significant bone development of your infant. Apart from its soothing and anti-microbial properties, it keeps your babys delicate and sensitive skin shielded from environmental pollutants that cause irritation. Khus Khus is another natural ingredient that has strong anti-perspirant and astringent properties. The antiseptic and healing powers of natural zinc found in this herbal baby powder are quite effective against conditions like Hyperhidrosis (excessive sweating) and Miliaria Rubra (commonly known as prickly heat). As the functioning of sweat glands is not developed to the fullest in infants, they are prone to sweat-related irritation, rashes and blisters',
        price: '63',
        qty: '5',
        _tags: ['baby-powder'],
        category: "baby-and-mom-care",
        composition: 'Olive Oil,Almond Oil,Khus Grass',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Himalaya',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '100gm'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/LACTOPJ04A/LACTOPJ04A-1.jpg?id=2020-04-08-08:48:58.246000',
        title: 'Lactogen Stage 2 Follow Up Formula Refill Refill',
        description: 'Lactogen Powder is a spray-dried follow-up milk substitute that gives daily nutrition to the baby. The ingredients help to improve immune function, develop brain and strengthen bones. It doesn t contain any artificial colors and preservatives.',
        price: '315',
        qty: '5',
        _tags: ['baby-nutrition'],
        category: "baby-and-mom-care",
        composition: 'Milk Solids, Maltodextrin, Demineralised Whey, Soyabean Oil, Corn Oil, Minerals, Soya Lecithin, Vitamins and Acidity Regulator (Citric Acid)',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Lactogen',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '400gm'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/ENOLEPB01A/ENOLEPB01A.jpg?id=2020-04-08-08:41:04.109000',
        title: 'Eno Lemon Flavour Sachet ',
        description: 'Eno Lemon Powder is an antacid which gives relief from any gastric discomfort, heartburn, bloating and stomach upset. It contains a permitted sweetener, Sodium Saccharin 33mg/5g and permitted colors, Sunset Yellow, Indigo Carmine, Tartrazine and Carmoisine. Permitted flavors added q.s.It is known to provide relief in 6 seconds.',
        price: '8',
        qty: '5',
        _tags: ['Indigestion'],
        category: "health-conditions",
        composition: 'Svarjiksara(Shudh) 2. 3 gm,Nimbukamlam(Shushkam) 2. 15 gm,Permitted Sweetener,Sodium Saccharin 5 mgPermitted Colours,Brilliant Blue FCF & Tartrazine.Permitted Flavours Added q. s. Contains No Fruit Pulp or Fruit Extracts.',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Eno',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '5gm'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/VICKSLB02A/VICKSLB02A-1.jpg?id=2020-04-08-08:48:56.143000',
        title: 'Vicks Vaporub Liniment',
        description: 'Vicks vapourub is a multi-purpose liniment that relieves 6 cold symptoms: breathing difficulty, body ache, cough, blocked nose, headache & muscular stiffness. Pudinah ke phool, Karpoor, Ajwain ke phool, Tarpin ka tail, Nilgiri tail, and Jatiphal tail are the active ingredients which help to breathe easily within 5 min',
        price: '130',
        qty: '5',
        _tags: ['cough','cold'],
        category: "health-conditions",
        composition: 'Pudinah ke phool, Karpoor, Ajwain ke phool, Tarpin ka tail, Nilgiri tail, and Jatiphal tail.Suitable for adults and children above 2 years old.        ',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Vicks',
        precautions: 'Store in a cool place. Keep away from direct sunlight. Keep away from children',
        tablets: '50 ml'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/LIV52TN01A/LIV52TN01A-1.jpg?id=2020-04-08-08:49:11.083000',
        title: 'Himalaya Liv 52 DS',
        description: 'Himalaya Liv 52 DS (Double Strength) is a hepatospecific formulation designed to improves the efficiency of the liver. It has antioxidant properties that help to prevent and treat viral hepatitis, alcoholic liver disease, pre-cirrhotic conditions and early cirrhosis, anorexia, loss of appetite and liver damage due to radiation therapy.        ',
        price: '126',
        qty: '5',
        _tags: [],
        category: "health-conditions",
        composition: 'The Caper Bush (Himsra) - 130 mg,Chicory (Kasani) - 130 mgMandur bhasma - 66 mgKakamachi - 64 mgArjuna - 64 mgKasamarda - 32 mg Jhavuka - 32 mg        ',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Himalaya',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '60 Tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/VOLINSN01A/VOLINSN01A-1.jpg?id=2020-04-08-08:48:56.231000',
        title: 'Volini Spray',
        description: 'Shake well before each use. Spray the contents from 5 cm distance on the affected areas 3-4 times in a day or, as directed by the physician.',
        price: '117',
        qty: '5',
        _tags: ['backache'],
        category: "health-conditions",
        composition: 'Diclofenac Diethylamine,Methyl Salicylate,Menthol',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Volini',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '40 gm'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/ZANDUBB02A/ZANDUBB02A.jpg?id=2020-04-08-08:40:59.293000',
        title: 'Zandu Balm',
        description: 'Zandu Balm is an Ayurvedic remedy for all regular pains like headache, backache and cold. It consists of powerful ayurvedic herbs that relieve pain instantly. Dermatologically tested and safe for skin.',
        price: '36',
        qty: '5',
        _tags: ['cold','bodyache','headache'],
        category: "health-conditions",
        composition: 'Mentha Sp. Satva: 14.0%, Gaultheria Fragrantissima :OL. 12.0%, Eucalyptus Globulus: OL. 0.80%, Base q.s.',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Zandu',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '8ml'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/DRRECDB80A/DRRECDB80A.jpg?id=2020-04-08-08:49:29.761000',
        title: 'Dr. Reckeweg R73 Joint Pain Drops',
        description: 'Use as directed by the doctor',
        price: '235',
        qty: '5',
        _tags: ['Bone joint'],
        category: "homeopathy",
        composition: 'Refer packing',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Dr. Reckeweg',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '22 ml'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/SBLHOTB01A/SBLHOTB01A.jpg?id=2020-04-08-08:49:06.604000',
        title: 'SBL Homeocal for Osteoporosis',
        description: 'Homeocal tablet is used in the pre post-menopausal period, osteoporosis, other associated symptoms like joint pains, backache, neck pain. SBL Homeocal tablets minimize the effects of hormonal imbalance during pre post-menopausal period. It restores proper metabolism and absorption of essential nutrients needed for optimum bone health and relieves symptoms of osteoporosis.',
        price: '140',
        qty: '5',
        _tags: ['Bone joint'],
        category: "homeopathy",
        composition: 'Calcarea carbonica 3x,Calcarea fluorica 3x,Calcarea phosphorica 3x,Silicea 3x,xcipients q.s',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'SBL ',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '25gm'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/SBLORSB02A/SBLORSB02A.jpg?id=2020-04-08-08:48:53.916000',
        title: 'SBL Orthomuv Syrup',
        description: 'Getting old never goes easy on you, you start having problems regarding your health. Your physical structure becomes weak, your bones start to soften and muscles start to tighten your legs and joints start to hurt all around. That is why Orthomuv from SBL which is a liquid based syrup tends to treat such complications regarding muscles, joint pain and inflammation. Ingredients include Arnica montana, Bryonia alba, Dulcamara along with many more such ingredients chosen in particular to aid and support your recovery from muscle pulls and sprains, along with treating conditions like arthritis.',
        price: '275',
        qty: '5',
        _tags: ['Bone joint'],
        category: "homeopathy",
        composition: 'Arnica montana,Bryonia alba,Dulcamara,Rhus toxicodendron,Gaultheria procumbens,Acidum benzoicum,Kali iodatum',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'SBL',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '500ml'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/BAKSOTB27A/BAKSOTB27A.jpg?id=2020-04-08-08:51:38.307000',
        title: 'Baksons Y - Lax',
        description: 'An effective formulation with laxative action combining the valuable Homoeopathic remedies and an additional constituent phenolphthalein that tones up the intestines, regulates bowel habits, relieves constipation & anal itching. Also relieves the associated complaints of bloated sensation, flatulence, abdominal pain & straining during defecation.',
        price: '323',
        qty: '5',
        _tags: ['Digestive aid'],
        category: "homeopathy",
        composition: 'Phenolphthalein 1x,Senna 1x,Sulphur 1x',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Baksons',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '350Tablets'
    }),
    new Product({
        image: 'https://cdn.medlife.com/productImages/DRRECDB17A/DRRECDB17A.jpg?id=2020-04-08-08:49:29.934000',
        title: 'Dr. Reckeweg R5 Stomach Drops ',
        description: 'Use As directed by the doctor        ',
        price: '234',
        qty: '5',
        _tags: ['Digestive aid'],
        category: "homeopathy",
        composition: 'Refer package',
        mfgDate: '10/02/2019',
        expDate: '10/02/2022',
        brand: 'Dr. Reckeweg ',
        precautions: 'Keep away from direct sunlight,Store in a dry place',
        tablets: '22ml'
    }),
]

var done=0;
User.remove({}, function(err, result){
    if(err){
        console.log("Error ", err);
    } else {
        console.log("Removed all");
    }
});
/*for(var i=0; i<products.length; i++){
    products[i].save(function(err,result){
        done++;
        console.log(done);
        if(done === products.length){
            exit();
        }
    });
}


function exit(){
    mongoose.disconnect();
}*/